##
# Copyright (c) 2025 Analog Devices, Inc. All Rights Reserved.
# This software is proprietary and confidential to Analog Devices, Inc. and its licensors.
##

name: 'Update M2k build status'

description:
  'Workflow to update status of m2k build'

on:
  workflow_dispatch:
    inputs:
      private-run:
        required: true
        type: string

jobs:
  build-update-status:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update status
        shell: sh
        run: |
          ./CI/sync-workflow.sh
        env:
          PRIVATE_ORG: ${{ secrets.PRIVATE_ORG }}
          PRIVATE_REPO: ${{ secrets.PRIVATE_REPO }}
          PRIVATE_RUN: ${{ inputs.private-run }}
          GH_TRIGGER_TOKEN: ${{ secrets.GH_TRIGGER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}